apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: secops
spec:
  containers: 
    - image: httpd:alpine
      name: httpd

---

apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: secops
spec:
  ports:
    - port: 81
      protocol: TCP
      targetPort: 80
  type: ClusterIP


